language: php

php:
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - make symfony.dev.rebuild

script:
  - make symfony.test.bdd suite=quickstart_app config=test/behat.yml
  - make symfony.test.unit suite=app
  - make symfony.test.spec config=test/phpspec.yml
  - make scrutinizer.coverage

after_failure:
  - make symfony.logs

env:
  global:
    - secure: U1TFca6LeHYWKiBJznqjO7c8F8sK63OnH37O/v+9N/wvp9YBusDzJ0NyerFbxce4c28ZL1JFUQUgAqeHOzDFjHdqY7sHD8YHSUEZS9ZCjXsfnKnEIPY/HOCOOED7dYZrLp6NZFF1B3BoosguFTenEMT2XEc1DsmwfHk3aqLYNes=

deploy:
  provider: heroku
  api_key:
    secure: Z3ayUw0ugCox7Dyvw5o1L3xCySlf8R5Pi124xffqvw5A/jnvi6yyZ/bUvwonNWTYhsR2WydAjgz9KFSjhgUEUNQpHa+rpSMpiZCCkmblAhdakHHVo9AR3X165sM/VGLFVnC69XkfvS/F8l6iAqoyWQAdjaR6GLtnY/dxgMmavko=
  app: symfony-quickstart
  on:
    all_branches: true
  run:
      - "make symfony.dev.rebuild"
